package FieldsInXML.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;

public class TableColumn_SubstituteMenu extends SubstituteMenuBase {
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new TableColumn_SubstituteMenu.SMP_ReferenceScope_3q4ysa_a(), MetaAdapterFactory.getConcept(0x8b4ff03b42b94888L, 0xa81e703bddc7697eL, 0x55057c6570163db2L, "FieldsInXML.structure.TableColumn")));
    return result;
  }

  @NotNull
  @Override
  public List<SubstituteMenuItem> createMenuItems(@NotNull SubstituteMenuContext context) {
    context.getEditorMenuTrace().pushTraceInfo();
    context.getEditorMenuTrace().setDescriptor(new EditorMenuDescriptorBase("default substitute menu for TableColumn. Generated from implicit smart reference attribute.", new SNodePointer("r:413663fe-496c-43e4-87e1-97a30338a031(FieldsInXML.structure)", "6126439643221474738")));
    try {
      return super.createMenuItems(context);
    } finally {
      context.getEditorMenuTrace().popTraceInfo();
    }
  }


  public static class SMP_ReferenceScope_3q4ysa_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_3q4ysa_a() {
      super(MetaAdapterFactory.getConcept(0x8b4ff03b42b94888L, 0xa81e703bddc7697eL, 0x55057c6570163db2L, "FieldsInXML.structure.TableColumn"), MetaAdapterFactory.getReferenceLink(0x8b4ff03b42b94888L, 0xa81e703bddc7697eL, 0x55057c6570163db2L, 0x55057c65701739a5L, "field"));
    }
    @NotNull
    @Override
    public List<SubstituteMenuItem> createItems(SubstituteMenuContext context) {
      context.getEditorMenuTrace().pushTraceInfo();
      context.getEditorMenuTrace().setDescriptor(new EditorMenuDescriptorBase("reference scope substitute menu part", null));
      try {
        return super.createItems(context);
      } finally {
        context.getEditorMenuTrace().popTraceInfo();
      }
    }

  }
}
